interface IMaGauge {
  function DISTRIBUTION (  ) external view returns ( address );
  function DURATION (  ) external view returns ( uint256 );
  function TOKEN (  ) external view returns ( address );
  function _VE (  ) external view returns ( address );
  function _balances ( uint256 ) external view returns ( uint256 );
  function _depositEpoch ( uint256 ) external view returns ( uint256 );
  function _periodFinish (  ) external view returns ( uint256 );
  function _start ( uint256 ) external view returns ( uint256 );
  function _totalSupply (  ) external view returns ( uint256 );
  function balanceOfToken ( uint256 tokenId ) external view returns ( uint256 );
  function claimFees (  ) external returns ( uint256 claimed0, uint256 claimed1 );
  function deposit ( uint256 amount ) external returns ( uint256 _tokenId );
  function depositAll (  ) external returns ( uint256 _tokenId );
  function earned ( uint256 _tokenId ) external view returns ( uint256 );
  function external_bribe (  ) external view returns ( address );
  function fees0 (  ) external view returns ( uint256 );
  function fees1 (  ) external view returns ( uint256 );
  function gaugeRewarder (  ) external view returns ( address );
  function getReward ( uint256 _tokenId ) external;
  function internal_bribe (  ) external view returns ( address );
  function isForPair (  ) external view returns ( bool );
  function lastTimeRewardApplicable (  ) external view returns ( uint256 );
  function lastUpdateTime (  ) external view returns ( uint256 );
  function maGaugeId (  ) external view returns ( uint256 );
  function maNFTs (  ) external view returns ( address );
  function maturityLevelOfTokenMaxArray ( uint256 _tokenId ) external view returns ( uint256 _matLevel );
  function maturityLevelOfTokenMaxBoost ( uint256 _tokenId ) external view returns ( uint256 _matLevel );
  function notifyRewardAmount ( address token, uint256 reward ) external;
  function owner (  ) external view returns ( address );
  function periodFinish (  ) external view returns ( uint256 );
  function renounceOwnership (  ) external;
  function rewardForDuration (  ) external view returns ( uint256 );
  function rewardPerToken (  ) external view returns ( uint256 );
  function rewardPerTokenStored (  ) external view returns ( uint256 );
  function rewardRate (  ) external view returns ( uint256 );
  function rewardToken (  ) external view returns ( address );
  function rewards ( uint256 ) external view returns ( uint256 );
  function setDistribution ( address _distribution ) external;
  function setGaugeRewarder ( address _gaugeRewarder ) external;
  function totalSupply (  ) external view returns ( uint256 );
  function totalWeight (  ) external view returns ( uint256 _totalWeight );
  function transferOwnership ( address newOwner ) external;
  function updateReward ( uint256 _tokenId ) external;
  function userRewardPerTokenPaid ( uint256 ) external view returns ( uint256 );
  function weightOfToken ( uint256 _tokenId ) external view returns ( uint256 );
  function withdraw ( uint256 _tokenId ) external;
  function withdrawAndHarvest ( uint256 _tokenId ) external;
}
